backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: 'signatures'
    label: 'Signatures'
    folder: "_data/signatures"
    create: true
    identifier_field: name
    extension: json
    format: json
    editor:
      preview: false
    fields:
      - { label: Image, name: img, widget: image }
      - { label: Name, name: name, widget: string, required: true, hint: '2:3 ratio is used. minimum 100px x 150px required' }
      - { label: Title, name: title, widget: string }
      - { label: Phone, name: phone, widget: string, required: false }
