backend:
  name: o2o-signatures
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: 'data'
    label: 'Data'
    files:
      - label: 'Signatures'
        name: 'signatures'
        file: 'data.json'
        fields:
          - label: Signatures
            name: signatures
            widget: list
            fields:
              - { label: Image, name: img, widget: string }
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Phone, name: phone, widget: string }
